/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIInsightPanel: typeof import('./components/editor/AIInsightPanel.vue')['default']
    AISettingsPanel: typeof import('./components/workspace/AISettingsPanel.vue')['default']
    Badge: typeof import('./components/ui/Badge.vue')['default']
    Button: typeof import('./components/ui/Button.vue')['default']
    CommandPalette: typeof import('./components/CommandPalette.vue')['default']
    DataTable: typeof import('./components/ui/DataTable.vue')['default']
    DraftNotificationBanner: typeof import('./components/ui/DraftNotificationBanner.vue')['default']
    EmptyState: typeof import('./components/ui/EmptyState.vue')['default']
    ExportDialog: typeof import('./components/workspace/ExportDialog.vue')['default']
    MilkdownEditor: typeof import('./components/editor/MilkdownEditor.vue')['default']
    OrganizeGroupTree: typeof import('./components/organize/OrganizeGroupTree.vue')['default']
    OrganizeKanban: typeof import('./components/organize/OrganizeKanban.vue')['default']
    OrganizeSplit: typeof import('./components/organize/OrganizeSplit.vue')['default']
    OrganizeTable: typeof import('./components/organize/OrganizeTable.vue')['default']
    PageShell: typeof import('./components/layout/PageShell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./components/ui/SectionHeader.vue')['default']
    SkeletonLoader: typeof import('./components/ui/SkeletonLoader.vue')['default']
    SnippetListItem: typeof import('./components/workspace/SnippetListItem.vue')['default']
    TableOfContents: typeof import('./components/editor/TableOfContents.vue')['default']
    TagFilterBar: typeof import('./components/ui/TagFilterBar.vue')['default']
    TemplateDialog: typeof import('./components/workspace/TemplateDialog.vue')['default']
    UiConfirmDialogHost: typeof import('./components/ui/UiConfirmDialogHost.vue')['default']
    UiSelect: typeof import('./components/ui/UiSelect.vue')['default']
    UiToastViewport: typeof import('./components/ui/UiToastViewport.vue')['default']
    WorkspaceGroupManager: typeof import('./components/workspace/WorkspaceGroupManager.vue')['default']
    WorkspaceGroupTree: typeof import('./components/WorkspaceGroupTree.vue')['default']
    WorkspaceShareManager: typeof import('./components/workspace/WorkspaceShareManager.vue')['default']
    WorkspaceTagManager: typeof import('./components/workspace/WorkspaceTagManager.vue')['default']
  }
}
